In [2]:
print('Hello World!')
print('سلام جهان')

Hello World!
سلام جهان


In [3]:
#2.1
import random
n = random.randint(1,6)
print(n)

4


In [4]:
#2.2
a = int(input('1st number: ')) #if we dont define them as int, there will be an error. why?!
b = int(input('2nd number: '))
x = max(a,b)
y = min(a,b)

def mygcd(i,j):
    if j==0:
        return i
    else:
        return mygcd(j,i%j)
    
print(mygcd(x,y))

1st number: 18
2nd number: 96
6


In [20]:
#2.3
from datetime import date 
import math
from datetime import timedelta 
t = int(input('Enter the number of seconds: '))
D=math.floor(t/86400)
t=t%86400
H=math.floor(t/3600)
t=t%3600
M=math.floor(t/60)
t=t%60
S=t
P=date(1970, 1, 1)
P=P+timedelta(days=D)
print('Date & Time: '+P.strftime("%Y-%m-%d")+' '+str(H)+':'+str(M)+':'+str(S))

Enter the number of seconds: 1000000000
Date & Time: 2001-09-09 1:46:40


In [21]:
#2.4.a
def LD(a, b):
    if a == "":
        return len(b)
    if b == "":
        return len(a)
    if a[0] == b[0]:
        cost = 0
    else:
        cost = 1
       
    res = min([LD(a[1:], b)+1,
               LD(a, b[1:])+1, 
               LD(a[1:], b[1:]) + cost])

    return res

a = str(input('1st string: '))
b = str(input('2nd string: '))

print(LD(a, b))

1st string: abcdefg
2nd string: abefg
2


In [22]:
#2.4.b
def collatz1(n):
    count = 1
    print(n,end=' ')
    while 1:
        count+=1
        if n%2:    #odd
            n = 3*n + 1
        else:      #even
            n = int(n/2)
        print(n,end=' ')
        if(n==1):
            break
    print('\nthe length of the sequence:', count)

n = int(input('Enter an integer:'))
collatz1(n)


Enter an integer:21322
21322 10661 31984 15992 7996 3998 1999 5998 2999 8998 4499 13498 6749 20248 10124 5062 2531 7594 3797 11392 5696 2848 1424 712 356 178 89 268 134 67 202 101 304 152 76 38 19 58 29 88 44 22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
the length of the conjucture: 57


In [23]:
#2.5
def collatz1(n):
    count = 1
    print(n,end=' ')
    while 1:
        count+=1
        if n%2:    #odd
            n = 3*n + 1
        else:      #even
            n = int(n/2)
        print(n,end=' ')
        if(n==1):
            break
    print('\nthe length of the sequence:', count)

def collatz2(n):
    count = 1
    while 1:
        count+=1
        if n%2:    #odd
            n = 3*n + 1
        else:      #even
            n = int(n/2)
        if(n==1):
            break
    return count

a = []
for i in range(1,1000):
    a.append(collatz2(i))

m = a.index(max(a))
print(m+1, 'has the largest sequence')
collatz1(m+1)


871 has the largest sequence
871 2614 1307 3922 1961 5884 2942 1471 4414 2207 6622 3311 9934 4967 14902 7451 22354 11177 33532 16766 8383 25150 12575 37726 18863 56590 28295 84886 42443 127330 63665 190996 95498 47749 143248 71624 35812 17906 8953 26860 13430 6715 20146 10073 30220 15110 7555 22666 11333 34000 17000 8500 4250 2125 6376 3188 1594 797 2392 1196 598 299 898 449 1348 674 337 1012 506 253 760 380 190 95 286 143 430 215 646 323 970 485 1456 728 364 182 91 274 137 412 206 103 310 155 466 233 700 350 175 526 263 790 395 1186 593 1780 890 445 1336 668 334 167 502 251 754 377 1132 566 283 850 425 1276 638 319 958 479 1438 719 2158 1079 3238 1619 4858 2429 7288 3644 1822 911 2734 1367 4102 2051 6154 3077 9232 4616 2308 1154 577 1732 866 433 1300 650 325 976 488 244 122 61 184 92 46 23 70 35 106 53 160 80 40 20 10 5 16 8 4 2 1 
the length of the sequence: 179


In [28]:
#3.1
list1 = []
list1.append(96101816)
list1.append('Hadi')
print(list1)

list2 = []
list2.append(96102201)
list2.append('mojtaba')

list3 = []
list3.append(96101849)
list3.append('Shoara')

list1.append(list2)
list1.append(list3)
print(list1)
print(list1[2][1])

#now lets use extend
list1.extend(list2)
list1.extend(list3)
print(list1)

[96101816, 'Hadi']
[96101816, 'Hadi', [96102201, 'mojtaba'], [96101849, 'Shoara']]
mojtaba
[96101816, 'Hadi', [96102201, 'mojtaba'], [96101849, 'Shoara'], 96102201, 'mojtaba', 96101849, 'Shoara']


In [27]:
#3.2
#tuple is ordered, but unchangeable; no add, no remove
a = ("apple",) #comma needed for single element tuple
print(type(a))

#NOT a tuple
a = ("apple")
print(type(a))

#can define a tuple by declaring it's type as tuple
a = tuple(("apple"))
print(type(a))

#duplicate members
a = ((1,1),2,3)       
print(a)

<class 'tuple'>
<class 'str'>
<class 'tuple'>
((1, 1), 2, 3)


In [30]:
#3.3
import numpy
a = [[1,0,0,0,1],
     [0,0,0,0,0],
     [0,0,1,0,0]]
b = numpy.nonzero(a)
for i in range(len(b)):
    map(list,b[i])

d = []
for i in range(len(a)):
    for j in range(len(a[0])):
        d.append( sum(abs(b[0][:] - i)) + sum(abs(b[1][:] - j)) )

distance = min(d)
index = d.index(distance)
row = index//5
column = index-(5*row)
print(str((row,column)) +' is the centre of mass and has the distance of: ' + str(distance))

(array([0, 0, 2], dtype=int64), array([0, 4, 2], dtype=int64))
(0, 2) is the centre of mass and has the distance of: 6


In [31]:
#3.4
nation = ['Roman', 'Egypt', 'Greek', 'Chinese', 'Islamic', 'Mayan', 'Persian', 'Mongol']
golden_age = ['27BC-1453AD','3150BC-30BC','800BC-600AD','221BC-1912AD',
              '750AD-1257AD','2000BC-1540AD','550BC-651AD','1206AD-1368AD']
x = zip(nation, golden_age)
y = dict(x)
print(y)
print(y['Roman'])

{'Roman': '27BC-1453AD', 'Egypt': '3150BC-30BC', 'Greek': '800BC-600AD', 'Chinese': '221BC-1912AD', 'Islamic': '750AD-1257AD', 'Mayan': '2000BC-1540AD', 'Persian': '550BC-651AD', 'Mongol': '1206AD-1368AD'}
27BC-1453AD


In [41]:
#3.5
import numpy as np
a = [2**i for i in range(17)]
print(a)

b = [x*x for x in range(1,5)]
print(b)

c = [a[x] for x in b if x%2==0]
print(c)

#3.6
d = np.array([[(3*i+j)*(3*i+j) for j in range(3)] for i in range(3)])
print(d)

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536]
[1, 4, 9, 16]
[16, 65536]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
